export const EVENT_ADDED = 'EVENT_ADDED';
export const EVENT_DELETED = 'EVENT_DELETED';
export const EVENT_BABY_ASSIGNED = 'EVENT_BABY_ASSIGNED';
export const EVENT_BABY_UNASSIGNED = 'EVENT_BABY_UNASSIGNED';
